#!/usr/bin/env sh

SCRIPT="$(basename $0)"
TOUCH="$(which touch)"
CAT="$(which cat)"

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'
INFO="${GREEN}INFO:${NC}"
WARN="${YELLOW}WARN:${NC}"
FATAL="${RED}FATAL:${NC}"

PROFILE_FILE="$HOME/.config/ssm-ssh/config.properties"

print() {
    echo $* >&2
}

info() {
    echo ${INFO} $* >&2
}

warn() {
    echo ${WARN} $* >&2
}

fatal() {
    echo ${FATAL} $* >&2
    exit 1
}

v_info() {
    echo ${INFO} $* >&3
}

v_warn() {
    echo ${WARN} $* >&3
}

v_fatal() {
    echo ${FATAL} $* >&3
    exit 1
}

usage() {
    ${CAT} <<EOF >&2
Usage:
    ${SCRIPT} [OPTIONS] ip-address
    ${SCRIPT} [OPTIONS] ec2-instance-id
    ${SCRIPT} [OPTIONS] [-C | --cluster] cluster-name ecs-container-instance

Options:
    -h, --help
        Prints this help message and exits
    -S PROFILE, --set-default-profile PROFILE
        Sets the default profile for ${SCRIPT} to PROFILE
    -O PROFILE, --use-okta PROFILE
        Use Okta for SSO (SAML) authentication with PROFILE
    -G PROFILE, --use-google PROFILE
        Use Google for SSO (SAML) authentication with PROFILE
    -C CLUSTER, --cluster CLUSTER
        Required when the instance address is an ECS container instance
EOF
    exit $1
}

get_aws_default_profile() {
    if [ $# -ne 1 ]; then
        fatal "get_aws_default_profile takes 1 argument"
    fi
    if [ -f "${PROFILE_FILE}" ] && grep -q -E -e '^aws_profile=.+' "${PROFILE_FILE}"; then
        awk -F= '/^aws_profile/ { print $2 }' | tail -n1
    else
        log "No default AWS profile is set for $0"
        read -p "Enter a profile: " PROFILE >&2
        set_aws_profile ${PROFILE}
    fi
}

set_aws_profile() {
    if [ $# -ne 1 ]; then
        fatal "set_aws_profile takes 1 argument"
    fi
    if [ ! -f "${PROFILE_FILE}" ]; then
        mkdir -p "$(dirname "${PROFILE_FILE}")"
        touch "${PROFILE}"
    fi
    if grep -q -E -e '^aws_profile=.+' "${PROFILE_FILE}"; then
        ex -s "${PROFILE_FILE}" <<EDIT
/^aws_profile=..*/ s/^\(aws_profile=\).*\$/\1$1/
w
q
EDIT
    else
        echo "aws_profile=$1" | tee "${PROFILE}" >/dev/null
    fi
    info "AWS profile set to '$(get_aws_default_profile)'"
}

is_private_ip() {
    if [ $# -ne 1 ]; then
        fatal "is_private_ip takes 1 argument"
    fi
    echo $1 | grep -q -E -e '^(192\.168|10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.)'
}

ip_to_instance_id() {
    if [ $# -ne 1 ]; then
        fatal "ip_to_instance_id takes 1 argument"
    fi
    {
        if is_private_ip "$1"; then
            ${AWS_CMD} ec2 describe-instances --filter "Name=private-ip-address,Values='$1'"
        else
            ${AWS_CMD} ec2 describe-instances --filter "Name=ip-address,Values='$1'"
        fi
    } | jq .Reservations.Instances[0].InstanceId
}

ecs_container_instance_to_instance_id() {
    if [ $# -ne 2 ]; then
        fatal "ecs_container_instance_to_instance_id takes 1 argument"
    fi
    {
        ${AWS_CMD} ecs decribe-container-instances --cluster $1 --container-instances $2
    } | jq .containerInstances[0].ec2InstanceId
}

set_aws_cmd() {
    AWS_CMD="$(which aws)"
    if [ -z "${AWS_CMD}" ]; then
        fatal "The AWS CLI is not installed. Try running \`brew install awscli\`."
    fi

    if [ -z "${PROFILE}" ]; then
        PROFILE=$(get_aws_default_profile)
    fi

    if [ "${PROFILE_TYPE}" == "OKTA" ]; then
        if [ ! -f "${HOME}/.okta/okta-aws-cli.jar" ]; then
            fatal "Could not locate ~/.okta/okta-aws-cli.jar. Please make sure the Okta AWS CLI is installed."
        fi
        if ! java -version &>/dev/null; then
            fatal "Java is not installed. Try installing Java 8."
        else
            JAVA_CMD="$(which java)"
        fi
        AWS_CMD="env OKTA_PROFILE=${PROFILE} ${JAVA_CMD} -classpath ${HOME}/.okta/okta-aws-cli.jar com.okta.tools.WithOkta ${AWS_CMD} --profile ${PROFILE}"
    elif [ "${PROFILE_TYPE}" == "GOOGLE" ]; then
        if ! aws-google-auth --version; then
            true
        else
            GOOGLE_AUTH="$(which aws-google-auth)"
        fi
    fi
}

run_aws_cmd() {
    if [ -z "${AWS_CMD}" ]; then
        set_aws_cmd
    fi
    v_info Executing \'${AWS_CMD} $*\'
    echo ${AWS_CMD} $* | sh
}

exec 3>/dev/null

PROFILE_TYPE=
PROFILE=

while [ "x$1" != "x" ]; do
    option=$1
    shift
    args="${args} \"${option}\""
    
    case ${option} in 
        *=*)
            optarg=`echo ${option} | sed -e 's,^[^=]*=,,'`
            ;;
    esac

    case ${option} in 
        --help | -h)
            usage 0
            ;;
        --verbose | -v)
            exec 3>&2
            ;;
        --set-default-profile=*)
            set_aws_profile "${optarg}"
            exit 0
            ;;
        --set-default-profile | -S)
            set_aws_profile "$1"
            shift
            args="${args} \"${option}\""
            exit 0
            ;;
        --use-okta=*)
            PROFILE_TYPE="OKTA"
            PROFILE="${optarg}"
            ;;
        --use-okta | -O)
            PROFILE_TYPE="OKTA"
            PROFILE="$1"
            shift
            args="${args} \"${option}\""
            ;;
        --use-google=*)
            PROFILE_TYPE="GOOGLE"
            PROFILE="${optarg}"
            ;;
        --use-google | -G)
            PROFILE_TYPE="GOOGLE"
            PROFILE="$1"
            shift
            args="${args} \"${option}\""
            ;;
        --)
            break
            ;;
    esac
    v_info Parsed option ${option}
done


run_aws_cmd sts get-caller-identity
